name: swipefashion
homepage: swipefashion.com
dependencies:
  angular: '>=1.0.0 <2.0.0'
  browser: any
  lawndart: any
  uuid: any
  web_components: any
dev_dependencies:
  dartmocks: any
  guinness: '>=0.1.5 <0.2.0'
  unittest: any
transformers:
- angular:
    html_files:
    - lib/stack.html
