name: swipefashion
version: 0.1.0
dependencies:
  angular: '>=1.0.0 <2.0.0'
  browser: any
  lawndart: any
  uuid: any
  web_components: any
dev_dependencies:
  dartmocks: any
  guinness: any
  unittest: any
transformers:
- angular:
    html_files:
    - lib/stack.html
